pluginManagement {
    repositories {
        //mavenLocal()
        gradlePluginPortal()
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'BackendAzureDevOps'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':task-store-postgres'
project(':task-store-postgres').projectDir = file('./infrastructure/driven-adapters/task-store-postgres')
include ':agent-client'
project(':agent-client').projectDir = file('./infrastructure/driven-adapters/agent-client')
include ':reactive-web'
project(':reactive-web').projectDir = file('./infrastructure/entry-points/reactive-web')
include ':pgvector-store'
project(':pgvector-store').projectDir = file('./infrastructure/driven-adapters/pgvector-store')
include ':metrics'
project(':metrics').projectDir = file('./infrastructure/helpers/metrics')
include ':s3-repository'
project(':s3-repository').projectDir = file('./infrastructure/driven-adapters/s3-repository')
include ':report-storage-file'
project(':report-storage-file').projectDir = file('./infrastructure/driven-adapters/report-storage-file')
