package co.com.bancolombia.usecase.chat;

import co.com.bancolombia.model.a2a.Artifact;
import co.com.bancolombia.model.a2a.Message;
import co.com.bancolombia.model.a2a.Part;
import co.com.bancolombia.model.a2a.SendMessageRequest;
import co.com.bancolombia.model.a2a.SendMessageResponse;
import co.com.bancolombia.model.a2a.Task;
import co.com.bancolombia.model.a2a.TaskState;
import co.com.bancolombia.model.a2a.TaskStatus;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Construye las respuestas del protocolo A2A a partir del texto que produce un flujo.
 *
 * <p>Aísla el detalle del transporte (Task, Artifact, Message, metadatos) del caso de uso, que así
 * conserva una única razón para cambiar: orquestar la conversación.
 */
final class A2AResponseFactory {

    private static final String INTERNAL_ERROR = "INTERNAL_ERROR";
    private static final String KEY_EXECUTION_TIME_MS = "executionTimeMs";
    private static final String ERROR_PREFIX = "No pude completar la operación: ";
    private static final String UNKNOWN_ERROR = "unknown";

    private A2AResponseFactory() {
        // Fábrica sin estado
    }

    static String extractContextId(SendMessageRequest request) {
        return request != null && request.getMessage() != null
                ? request.getMessage().getContextId()
                : null;
    }

    static SendMessageResponse success(SendMessageRequest request, String llmResponse,
            long executionTimeMs) {
        String contextId = extractContextId(request);
        Message agentMessage = buildAgentMessage(contextId, llmResponse);

        Task task = Task.builder()
                .id(UUID.randomUUID().toString())
                .contextId(contextId)
                .status(buildStatus(TaskState.COMPLETED, agentMessage))
                .artifacts(List.of(
                        Artifact.builder()
                                .artifactId(UUID.randomUUID().toString())
                                .name("agent-response")
                                .description("Primary response generated by the consumer agent")
                                .parts(List.of(Part.ofData(Map.of(
                                        "response", llmResponse,
                                        KEY_EXECUTION_TIME_MS, executionTimeMs))))
                                .build()))
                .history(List.of(agentMessage))
                .metadata(Map.of(KEY_EXECUTION_TIME_MS, executionTimeMs))
                .build();

        return SendMessageResponse.builder().message(agentMessage).task(task).build();
    }

    static SendMessageResponse failure(SendMessageRequest request, long executionTimeMs,
            String errorMessage) {
        String contextId = extractContextId(request);
        Message agentMessage = buildAgentMessage(contextId, ERROR_PREFIX + errorMessage);

        Task task = Task.builder()
                .id(UUID.randomUUID().toString())
                .contextId(contextId)
                .status(buildStatus(TaskState.FAILED, agentMessage))
                .history(List.of(agentMessage))
                .metadata(Map.of(
                        KEY_EXECUTION_TIME_MS, executionTimeMs,
                        "errorCode", INTERNAL_ERROR,
                        "errorMessage", errorMessage == null ? UNKNOWN_ERROR : errorMessage))
                .build();

        return SendMessageResponse.builder().message(agentMessage).task(task).build();
    }

    private static TaskStatus buildStatus(TaskState state, Message agentMessage) {
        return TaskStatus.builder()
                .state(state)
                .message(agentMessage)
                .timestamp(nowIso())
                .build();
    }

    private static Message buildAgentMessage(String contextId, String text) {
        return Message.builder()
                .role("agent")
                .contextId(contextId)
                .messageId(UUID.randomUUID().toString())
                .parts(List.of(Part.ofText(text)))
                .build();
    }

    private static String nowIso() {
        return Instant.now().atOffset(ZoneOffset.UTC).format(DateTimeFormatter.ISO_INSTANT);
    }
}

