package co.com.bancolombia.model.a2a;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A2A Protocol v1.0 - Artifact. Tangible output generated by an agent during a task.
 */
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class Artifact {

    private String artifactId;
    private String name;
    private String description;
    private List<Part> parts;
}
